# Generated by Django 3.0.6 on 2020-05-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='категория',
        ),
        migrations.RemoveField(
            model_name='page',
            name='меню',
        ),
        migrations.AddField(
            model_name='page',
            name='categories',
            field=models.ManyToManyField(to='pages.Category', verbose_name='категория'),
        ),
        migrations.AddField(
            model_name='page',
            name='draft',
            field=models.BooleanField(default=False, verbose_name='черновик'),
        ),
        migrations.AddField(
            model_name='page',
            name='image',
            field=models.ImageField(blank=True, upload_to='page_images/', verbose_name='изображение'),
        ),
        migrations.AddField(
            model_name='page',
            name='menu',
            field=models.ManyToManyField(to='pages.Menu', verbose_name='меню'),
        ),
    ]
