# Generated by Django 3.0.6 on 2020-05-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200508_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='menu',
            field=models.ManyToManyField(blank=True, to='pages.Menu', verbose_name='меню'),
        ),
    ]
