# Generated by Django 3.0.5 on 2020-05-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200508_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='show_on_home',
            field=models.BooleanField(default=False, help_text='Показать на гланой странице', verbose_name='на главную'),
        ),
    ]
